#pragma once

#include <deque>
#include <map>
#include <optional>
#include <stdexcept>
#include <unordered_map>
#include <vector>

#include "Order.hpp"

namespace matching {

// Thrown for invalid input (non-positive price/quantity, unknown order id).
class OrderError : public std::runtime_error {
public:
    explicit OrderError(const std::string& what) : std::runtime_error(what) {}
};

// Single-symbol limit order book with price-time priority matching.
//
// Not thread-safe by itself -- by design. A matching engine should only ever
// be mutated by one thread at a time (see MatchingEngine/OrderQueue), which
// is how real exchanges avoid the correctness problems of concurrent
// matching against the same book. Thread-safety here lives at the boundary
// (the incoming order queue), not inside the book.
class OrderBook {
public:
    // Matches the incoming order against the resting book (price-time
    // priority) and rests any unfilled remainder. Returns the trades
    // generated by this order. Throws OrderError for invalid input.
    std::vector<Trade> addOrder(Order order);

    // Removes a resting (unfilled or partially filled) order. Returns false
    // if the order id is unknown (already fully filled or cancelled).
    bool cancelOrder(std::int64_t orderId);

    std::optional<double> bestBid() const;
    std::optional<double> bestAsk() const;

    std::size_t bidLevels() const { return bids_.size(); }
    std::size_t askLevels() const { return asks_.size(); }

    // Top `depth` price levels on each side, best price first, as
    // (price, total resting quantity at that level) pairs. Useful for
    // printing a book snapshot.
    std::vector<std::pair<double, std::int64_t>> bidDepth(std::size_t depth) const;
    std::vector<std::pair<double, std::int64_t>> askDepth(std::size_t depth) const;

private:
    struct OrderLocation {
        Side side;
        double price;
    };

    template <typename Book>
    std::vector<std::pair<double, std::int64_t>> depthOf(const Book& book, std::size_t depth) const;

    // Bids sorted best (highest) price first; asks sorted best (lowest)
    // price first. Each price level is a deque so the front is the
    // longest-resting order at that price -- this is what gives FIFO
    // "time priority" within a price level, matching in O(1) per fill.
    std::map<double, std::deque<Order>, std::greater<double>> bids_;
    std::map<double, std::deque<Order>> asks_;

    // orderId -> which side/price it rests at, for O(1)-ish cancellation
    // (map lookup is O(log levels), then a scan of just that one level).
    std::unordered_map<std::int64_t, OrderLocation> index_;
};

} // namespace matching
